apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-driver-storage-test
  resources:
    requests:
      storage: 8Gi