apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: csi-driver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-driver-clusterrole
subjects:
- kind: ServiceAccount
  name: csi-driver-service-account
  namespace: default
